version: '3.8'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./:/app
    networks:
      - app 
    depends_on:
      - "mysql"
      
  mysql:
    image: mysql:8.0.31
    restart: unless-stopped 
    tty: true 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel
    networks:
      - app
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
    - "1025:1025"
    - "8025:8025"
    networks:
    - app

networks:
  app:
    driver: bridge